# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e86b5bb4f44fb217b6fdc177be795545991c0a0b280774dff7ac06897293c9cf0d5763e56722961c7a83e910459b65df6529e136180ada46d6b782b26f2d12e

test:
  secret_key_base: f5e50baddaaa10d21f268f14965645bcad73169582e4cf657a66a03b90ef3df17872a84cb48690bed987db5c9a304e9de93139d60cf00921cf3d4ccb1466b0fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
